version: 2.1
orbs:
  node: circleci/node@5.1.0
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@3.1.4
jobs:
  build:
    executor: node/default
    steps:
      - checkout
      # Since my project uses submodules, I need to ensure those submoduls are pulled down as well.
      - run:
          name: Checkout Submodules
          command: |
            git submodule sync --recursive
            git submodule update --recursive --init
      # Install Frontend / Backend dependencies
      - run:
          name: Install Frontend Dependencies
          command: |
            npm run frontend:install
      - run:
          name: Install Backend Dependencies
          command: |
            npm run backend:install
      # Lint Frontend / Backend
      - run:
          name: Lint Frontend
          command: |
            npm run frontend:lint
      - run:
          name: Lint Backend
          command: |
            npm run backend:lint
      # Build Frontend / Backend
      - run:
          name: Build Frontend
          command: |
            npm run frontend:build
      - run:
          name: Build Backend
          command: |
            npm run backend:build
  deploy:
    executor: node/default
    steps:
      - checkout
      # Since my project uses submodules, I need to ensure those submoduls are pulled down as well.
      - run:
          name: Checkout Submodules
          command: |
            git submodule sync --recursive
            git submodule update --recursive --init
      # Setup AWS CLI and EB CLI for deploy steps
      - aws-cli/setup
      - eb/setup
      # Deploy Frontend - install dependencies, build, and deploy
      - run:
          name: Deploy Frontend
          command: |
            npm run frontend:install
            npm run frontend:build
            npm run frontend:deploy
      # Deploy Backend - install dependencies, build, and deploy
      - run:
          name: Deploy Backend
          command: |
            npm run backend:install
            npm run backend:build
            npm run backend:deploy

workflows:
  fullstackdeploy:
    jobs:
      - build:
          filters:
            branches:
              only: main
      - hold:
          filters:
            branches:
              only: main
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - hold
